BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            size_hint_x: 0.8
            text: '34'
        BoxLayout:
            size_hint_x: 0.2
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        text: '54.71756'
        color: (1, 1, 0, 1)